### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by liuguoqian** [akgulebubekir/PdfSharp.Maui#2]
in windowsmachine,"var pdfManager = new PdfManager();" will throw error:"System.Reflection.ReflectionTypeLoadException:“Unable to load one or more of the requested types.
Method 'SaveAsJpeg' in type 'PdfSharp.Maui.Platforms.Windows.WindowsImageSourceImpl' from assembly 'PdfSharp.Maui, Version=1.0.1.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.”"

in android,GeneratePdfFromView will throw error:
System.MissingMethodException: 'Method not found: void PdfSharpCore.Drawing.XGraphics.DrawImage(PdfSharpCore.Drawing.XImage,PdfSharpCore.Drawing.XRect,System.Threading.CancellationToken)'

why?Thanks.

**Comment by akgulebubekir** [comment]
It should be fixed with new [version](https://www.nuget.org/packages/PdfSharp.Maui/1.0.2)
