### ISSUE TITLE
Sample app crashing on Android

### ISSUE THREAD

**Issue by SarthakB26** [akgulebubekir/PdfSharp.Maui#4]
![image](https://github.com/akgulebubekir/PdfSharp.Maui/assets/125443207/3ae79648-74ef-4782-bc61-ff35c669448e)

**Comment by SarthakB26** [comment]
though it look like an issue in maui FileSystem.OpenAppPackageFileAsync method

**Comment by SarthakB26** [comment]
FileSystem.OpenAppPackageFileAsync(p.File).Result is returning null stream.So it might be maui issue.
Just letting you here.
Tried updating Maui version to 8.0.10 but issue persist

**Comment by NiranjanXamarin** [comment]
@akgulebubekir thanks alot I was also facing same issue and got resolved in 1.0.4 but now I have another issue there can you please check. 

Hi, I am using 1.0.4 version and I am having overlapping text issue. I have list of items to print in as table so I have used stacklayout with ItemsSoucre property to bind the list of items. It looks good on screen as I have given desense width, but when I use pdfgenerate GeneratePdfFromView(view,PageOrientation.Portrait, PageSize.A4, PdfStyle.Uniform); like this and pass whole view. its creating pdf but the data from columns are overlapping .
<img width="479" alt="Screenshot 2024-03-18 at 5 35 58 PM" src="https://github.com/akgulebubekir/PdfSharp.Maui/assets/67553572/6b141564-f7c0-474a-a7d6-18b440414196">

**Comment by akgulebubekir** [comment]
This is another issue. Please use #5 for the problem.
