### ISSUE TITLE
Text Overlapping

### ISSUE THREAD

**Issue by NiranjanXamarin** [akgulebubekir/PdfSharp.Maui#5]
Hi, I am using 1.0.4 version and I am having overlapping text issue. I have list of items to print in as table so I have used stacklayout with ItemsSoucre property to bind the list of items. It looks good on screen as I have given desense width, but when I use pdfgenerate GeneratePdfFromView(view,PageOrientation.Portrait, PageSize.A4, PdfStyle.Uniform); like this and pass whole view. its creating pdf but the data from columns are overlapping .  
<img width="479" alt="Screenshot 2024-03-18 at 5 35 58 PM" src="https://github.com/akgulebubekir/PdfSharp.Maui/assets/67553572/29526d9a-b3eb-4d09-8015-6277f32a58d9">

**Comment by NiranjanXamarin** [comment]
Can anyone please update

**Comment by akgulebubekir** [comment]
Seems like a bug.Labels should be wrapped/concentinated for the library.
