### ISSUE TITLE
Text Overlapping

### ISSUE THREAD

**Issue by NiranjanXamarin** [akgulebubekir/PdfSharp.Maui#6]
Hi, I am using 1.0.4 version and I am having overlapping text issue. I have list of items to print in as table so I have used stacklayout with ItemsSoucre property to bind the list of items. It looks good on screen as I have given desense width, but when I use pdfgenerate GeneratePdfFromView(view,PageOrientation.Portrait, PageSize.A4, PdfStyle.Uniform); like this and pass whole view. its creating pdf but the data from columns are overlapping .
<img width="479" alt="Screenshot 2024-03-18 at 5 35 58 PM" src="https://github.com/akgulebubekir/PdfSharp.Maui/assets/67553572/25db06ed-0e20-4d50-9b3e-8033d4751fde">

**Comment by akgulebubekir** [comment]
this issue is duplicated with #5 and resolved with version 1.0.5. Please use lastest version
